### ISSUE TITLE
Can't save anything else than JPG

### ISSUE THREAD

**Issue by cAyou** [andydbc/unity-texture-packer#2]
Hi there ! I've noticed on the TexturePackerWindow.cs that the getter/setter textureFormat is never changed but always used on the class. You update the variable _textureFormat but never use it anywhere. So when it comes to serialize the file, it will always choose jpg, which is annoying because I need the alpha channel ;)
Fixed on my side, I will let you fix it on the repo.
Thanks !

**Comment by jasior0000** [comment]
I've had the same issue and noticed the same bug. Also fixed it on my side. 

There are more and more people using this tool to create a mask map for HDRP and can't get it to work because of this bug. I've even picked it up 2 months ago during some experiments with HDRP and got rid of it, as I couldn't figure out why it wasn't working.

**Comment by andydbc** [comment]
Fixed in: https://github.com/andydbc/unity-texture-packer/commit/8af3bb5e9ac8d4b956c02ef1c0ac370339a2ed5d
